### ISSUE TITLE
Missing py.typed marker file

### ISSUE THREAD

**Issue by omar-abdelgawad** [ahmedheakl/drone-vis#41]
Hey, Was taking a look and noticed that the entire codebase is statically typed with mypy but there is no py.typed marker file in src/dronevis. This is not a serious issue since the package is used as an application instead of an api but still I can make a pull request with the py.typed and the following in the setup.cfg file.

```setup.cfg
[options.package_data]
dronevis = py.typed
```

**Comment by ahmedheakl** [comment]
Sure, go ahead!
